[package]
name = "novel-boom-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Terminal UI for novel-boom"

[dependencies]
anyhow = { workspace = true }
crossterm = { workspace = true }
novel-boom-core = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
